### ISSUE TITLE
Touchback-error when placing ball

### ISSUE THREAD

**Issue by lasseuth1** [njustesen/ffai#22]
It seems like there's an error while in the Touchback-procedure, where the environment tries to put the ball back into play. It should only be possible to give the ball to one of the team's own players. We have experienced this error while there are players on the field, so it is not caused by an empty field. 

Our model predicts the action PLACE_BALL on a position where none of our own players are standing, and because our model is only allowed to predict legal actions, we think it is a problem in the Touchback-procedure. 

The problem arise in the call to _self.ball.move_to(action.player.position)_ in the Touchback.step(), and it tries to use SELECT_PLAYER to give the ball to. However the player is set to None at this point, which causes the error.  

<img width="925" alt="Screenshot 2019-04-03 at 09 37 45" src="https://user-images.githubusercontent.com/48207671/55473394-ed2a1600-560e-11e9-8ab3-fdc08f897953.png">

<img width="1059" alt="Screenshot 2019-04-03 at 12 18 47" src="https://user-images.githubusercontent.com/48207671/55473440-08952100-560f-11e9-9b07-15e7bf8b6f6e.png">

<img width="932" alt="Screenshot 2019-04-03 at 12 51 03" src="https://user-images.githubusercontent.com/48207671/55473536-3d08dd00-560f-11e9-8090-2b4e60d6b9b3.png">

<img width="1662" alt="Screenshot 2019-04-03 at 12 51 34" src="https://user-images.githubusercontent.com/48207671/55473558-4abe6280-560f-11e9-8060-8a0bd94042a0.png">

**Comment by ChristopherJakobsen** [comment]
It looks like, the issue occurs when all players on the team are stunned / knocked down when touchback procedure tries to SELECT_PLAYER to give the ball.

The screenshot displays the issue.
![image](https://user-images.githubusercontent.com/26457072/55476242-5e20fc00-5616-11e9-9813-ab0a800d3843.png)

How should this be avoided?

**Comment by lasseuth1** [comment]
The reason why all players can be stunned in the Touchback-procedure, could be due to a pitch invasion or fans throwing rocks (we have experienced both). The fact that we are training on the smallest of board sizes, increases the risk of all players being stunned when a Touchback happens.

**Comment by p-d-moore** [comment]
I would suggest being able to select a stunned player in this case.  The ball will immediately scatter because they player cannot catch.  Technically, according to the rules, it may even be correct behavior that any player can be selected for a touch back (whether standing, prone, stunned or no hands). If chosen player cannot catch, then ball bounces 1 square, that same as for a failed catch?

There is one further extreme possibility - when there is only 1 player on the field, and a rock is thrown, removing said player, right before a touchback is awarded.  With no players left on the pitch, not sure what to do in this case.

**Comment by njustesen** [comment]
I implemented the simple solution of allowing all squares to be selected when none is available.
