### ISSUE TITLE
ModuleNotFoundError: No module named 'examples'.

### ISSUE THREAD

**Issue by nevertiree** [njustesen/ffai#28]
When I follow the instruction and run "python examples/server_example.py" on folder ffai/ , I got ModuleNotFoundError: No module named 'examples'.

There may be some python import bugs here.  When I move the example script to other directory and remove "examples" in import lines, this script can run successfully.

Thanks.

**Comment by greentec** [comment]
I experienced same issue.

**Comment by p-d-moore** [comment]
If you are using conda for package management, rather than install ffai as a module, an alternative is to add the path of the project to your environment.  A simple way to do this:
1. open anaconda prompt
2. activate conda_env  (whichever environment you created to run ffai under)
3. conda install conda-build
4. conda-develop path_to_ffai  (whever your ffai code folder sits)

Once you do this, imports relative to the root directory of your ffai project work just fine (within the conda environment of the project) whether you use vscode, pycharm, jupyter notebook or whatever.  Incidentally, to use pycharm, I usually find it's best to launch from a fully activated conda environment (i.e. run the executable from an anaconda prompt) rather than to run the executable / shortcut directly.

**Comment by greentec** [comment]
Some add: After actually entering conda_env, I was able to add the path through the `conda develop [PATH] ` command rather than `conda-develop [PATH]`. OS: windows 10, conda version: 4.3.30
